"""Export Service for ScholAR.

Generates publication-ready research reports in:
- LaTeX (.tex) with TikZ Evidence Graph diagrams and formal citation bibliography
- Markdown (.md) with ASCII evidence DAGs and exact tabular math proofs
"""

from __future__ import annotations

import json
from typing import Any

from backend.schemas.claims import VerificationReport
from backend.schemas.evidence_graph import EvidenceGraph, ReasoningPath
from backend.schemas.numeric_plan import NumericExecutionResult
from backend.schemas.reasoning import QuestionAnalysis


class ExportService:
    """Generates formal LaTeX and Markdown reports from multi-level reasoning traces."""

    @classmethod
    def export_to_markdown(
        cls,
        paper_id: str,
        query: str,
        answer: str,
        analysis: QuestionAnalysis,
        path: ReasoningPath | None = None,
        numeric_res: NumericExecutionResult | None = None,
        verification: VerificationReport | None = None,
    ) -> str:
        """Format reasoning trace as structured Markdown."""
        lines = [
            f"# ScholAR Multi-Level Reasoning Report: {paper_id}",
            f"**Query**: {query}  ",
            f"**Reasoning Level**: `{analysis.reasoning_level.value}`  ",
            f"**Target Modalities**: {', '.join(m.value for m in analysis.target_modalities)}  ",
            "",
            "## 1. Verified Synthesis",
            answer,
            "",
        ]

        if numeric_res:
            lines.extend([
                "## 2. Deterministic Tabular Arithmetic Proof",
                f"- **Operation**: `{numeric_res.operation.value}`",
                f"- **Exact Computed Value**: `{numeric_res.formatted_value}`",
                f"- **Statement**: {numeric_res.formatted_statement}",
                "",
            ])

        if path and path.steps:
            lines.extend([
                "## 3. Evidence Reasoning Path (DAG)",
                "```",
            ])
            steps_str = " -> ".join(f"[{s.step_index}. {s.section or s.evidence_id} (p.{s.page})]" for s in path.steps)
            lines.extend([
                steps_str,
                "```",
                "",
                "### Detailed Evidence Nodes",
            ])
            for s in path.steps:
                mode_val = getattr(s.reasoning_mode, "value", str(s.reasoning_mode))
                subgoal_text = f" — *Subgoal: {s.subgoal}*" if s.subgoal else ""
                lines.append(f"- **Step {s.step_index}** [`{mode_val}`] (`{s.evidence_id}`, Page {s.page}, Role: `{s.role}`){subgoal_text}: {s.claim_contribution}")
            lines.append("")

        if verification:
            lines.extend([
                "## 4. 3-Way Atomic Claim Entailment Audit",
                f"- **Overall Status**: {'🟢 FULLY SUPPORTED' if verification.overall_supported else '🟡 PARTIAL / CAVEAT'}",
                f"- **Verified Claims**: {verification.supported_count} | **Caveats**: {verification.unsupported_count} | **Contradictions**: {verification.contradicted_count}",
                "",
                "### Atomic Claims",
            ])
            for c in verification.claims:
                status_icon = "🟢" if c.entailment_status.value == "SUPPORTED" else ("🔴" if c.entailment_status.value == "CONTRADICTED" else "🟡")
                lines.append(f"- {status_icon} **[{c.claim_id}]** `{c.entailment_status.value}`: {c.text}")
                if c.rationale:
                    lines.append(f"  - *Rationale*: {c.rationale}")
            lines.append("")

        lines.extend([
            "---",
            "*Generated by ScholAR (EACL 2027 Industry Track System) · 100% Local Execution with Software-Owned Provenance*",
        ])
        return "\n".join(lines)

    @classmethod
    def export_to_latex(
        cls,
        paper_id: str,
        query: str,
        answer: str,
        analysis: QuestionAnalysis,
        path: ReasoningPath | None = None,
        numeric_res: NumericExecutionResult | None = None,
        verification: VerificationReport | None = None,
    ) -> str:
        """Format reasoning trace as a standalone LaTeX document with TikZ diagram."""
        safe_q = query.replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")
        safe_ans = answer.replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")

        tikz_nodes = []
        tikz_edges = []
        if path and path.steps:
            for idx, s in enumerate(path.steps):
                sec_clean = (s.section or s.evidence_id).replace("_", "\\_")
                mode_clean = getattr(s.reasoning_mode, "value", str(s.reasoning_mode)).replace("_", "\\_")
                tikz_nodes.append(f"\\node[draw, rounded corners, fill=purple!10, text width=3.8cm, align=center] (n{idx+1}) at ({idx*4.4}, 0) {{\\textbf{{Step {s.step_index}: {mode_clean}}}\\\\{sec_clean}\\\\\\footnotesize Page {s.page}}};")
                if idx > 0:
                    tikz_edges.append(f"\\draw[->, thick, purple!70] (n{idx}) -- (n{idx+1});")

        tikz_code = "\n".join(tikz_nodes) + "\n" + "\n".join(tikz_edges)

        tex_content = f"""\\documentclass{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{tikz}}
\\usepackage{{geometry}}
\\usepackage{{booktabs}}
\\usepackage{{xcolor}}
\\geometry{{margin=1in}}

\\title{{\\textbf{{ScholAR Multi-Level Reasoning Report}}\\\\\\large Document ID: \\texttt{{{paper_id}}}}}
\\author{{ScholAR Research Assistant (EACL 2027)}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

\\section{{Research Query \\& Classification}}
\\textbf{{Query:}} {safe_q}\\\\
\\textbf{{Reasoning Depth:}} \\texttt{{{analysis.reasoning_level.value}}}\\\\
\\textbf{{Target Modalities:}} {', '.join(m.value for m in analysis.target_modalities)}

\\section{{Synthesized Answer}}
{safe_ans}

\\section{{Evidence Reasoning Path (DAG)}}
\\begin{{figure}}[h!]
\\centering
\\begin{{tikzpicture}}[node distance=1.5cm, auto]
{tikz_code}
\\end{{tikzpicture}}
\\caption{{Directed Evidence Reasoning Path connecting cross-section mechanisms, ablations, and empirical results.}}
\\end{{figure}}

\\section{{3-Way Atomic Claim Entailment Audit}}
\\begin{{itemize}}
"""
        if verification:
            for c in verification.claims:
                safe_claim = c.text.replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")
                tex_content += f"\\item \\textbf{{[{c.claim_id}]}} (\\texttt{{{c.entailment_status.value}}}): {safe_claim}\n"

        tex_content += """\\end{itemize}

\\vfill
\\noindent\\rule{\\textwidth}{0.4pt}\\\\
\\footnotesize Generated by ScholAR · 100\\% Local Compute · Zero Cloud Data Egress

\\end{document}
"""
        return tex_content
