from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field

from backend.schemas.document import BoundingBox, VisualRegion


class GroundingProposal(BaseModel):
    """Proposal generated by a VLM indicating supporting subregions inside a figure crop."""
    claim_id: str
    evidence_id: str
    regions: list[BoundingBox] = Field(default_factory=list)
    rationale: str | None = None
    proposer_model_id: str = "qwen3.5:9b"
    proposer_revision: str | None = None


class VisualGroundingValidator:
    """Validates geometry and maps crop-relative normalized boxes back to PDF page coordinates."""

    @staticmethod
    def validate_crop_box(box: BoundingBox, min_area: float = 0.001) -> BoundingBox | None:
        """Validate and clip normalized coordinates inside [0.0, 1.0]. Returns None if degenerate."""
        clipped = box.clip_to_bounds(min_x=0.0, min_y=0.0, max_x=1.0, max_y=1.0)
        if not clipped.is_valid(min_area=min_area):
            return None
        return clipped

    @staticmethod
    def map_crop_to_page(
        crop_region: BoundingBox,
        parent_page_box: BoundingBox,
    ) -> BoundingBox:
        """Map normalized crop coordinates [0.0, 1.0] to normalized page coordinates [0.0, 1.0]."""
        p_x0, p_y0, p_x1, p_y1 = parent_page_box.x0, parent_page_box.y0, parent_page_box.x1, parent_page_box.y1
        pw = p_x1 - p_x0
        ph = p_y1 - p_y0

        page_x0 = p_x0 + crop_region.x0 * pw
        page_y0 = p_y0 + crop_region.y0 * ph
        page_x1 = p_x0 + crop_region.x1 * pw
        page_y1 = p_y0 + crop_region.y1 * ph

        return BoundingBox(
            x0=round(page_x0, 4),
            y0=round(page_y0, 4),
            x1=round(page_x1, 4),
            y1=round(page_y1, 4),
            coordinate_space="normalized_page",
        )

    @staticmethod
    def expand_region(
        box: BoundingBox,
        expand_fraction: float = 0.20,
    ) -> BoundingBox:
        """Expand a bounding box around its center by a fraction (e.g. 20%), clipped to [0, 1]."""
        cx = (box.x0 + box.x1) / 2.0
        cy = (box.y0 + box.y1) / 2.0
        w = box.width * (1.0 + expand_fraction)
        h = box.height * (1.0 + expand_fraction)

        x0 = max(0.0, cx - w / 2.0)
        y0 = max(0.0, cy - h / 2.0)
        x1 = min(1.0, cx + w / 2.0)
        y1 = min(1.0, cy + h / 2.0)

        return BoundingBox(
            x0=round(x0, 4),
            y0=round(y0, 4),
            x1=round(x1, 4),
            y1=round(y1, 4),
            coordinate_space=box.coordinate_space,
        )


class VisualGroundingService:
    """Service to process subregion visual proposals and build verified visual regions."""

    @classmethod
    def extract_subregion_proposals(
        cls,
        vlm_text: str,
        evidence_id: str,
        model_id: str = "qwen3.5:9b",
    ) -> GroundingProposal:
        """Extract subregion bounding boxes from VLM text output."""
        import json
        import re

        regions: list[BoundingBox] = []
        
        # 1. Look for explicit JSON block or array
        json_matches = re.findall(r"(\[[\s\S]*?\]|\{[\s\S]*?\})", vlm_text)
        for match in json_matches:
            try:
                parsed = json.loads(match)
                items = parsed if isinstance(parsed, list) else parsed.get("subregions", [])
                if isinstance(items, list):
                    for item in items:
                        if not isinstance(item, dict):
                            continue
                        # Accept various coordinate key conventions
                        raw_box = item.get("box") or item.get("bbox") or item.get("box_2d") or item.get("coordinates")
                        if isinstance(raw_box, (list, tuple)) and len(raw_box) == 4:
                            y0, x0, y1, x1 = raw_box if raw_box[0] <= 1.0 or raw_box[0] > raw_box[1] else (raw_box[1], raw_box[0], raw_box[3], raw_box[2])
                            # If scale is 0..1000, normalize to 0..1
                            scale = 1000.0 if max(raw_box) > 1.0 else 1.0
                            regions.append(
                                BoundingBox(
                                    x0=min(x0, x1) / scale,
                                    y0=min(y0, y1) / scale,
                                    x1=max(x0, x1) / scale,
                                    y1=max(y0, y1) / scale,
                                    coordinate_space="normalized_page",
                                )
                            )
                        elif all(k in item for k in ("x0", "y0", "x1", "y1")):
                            scale = 1000.0 if max(item["x0"], item["x1"], item["y0"], item["y1"]) > 1.0 else 1.0
                            regions.append(
                                BoundingBox(
                                    x0=float(item["x0"]) / scale,
                                    y0=float(item["y0"]) / scale,
                                    x1=float(item["x1"]) / scale,
                                    y1=float(item["y1"]) / scale,
                                    coordinate_space="normalized_page",
                                )
                            )
            except Exception:
                continue

        # 2. Regex fallback for coordinate tuples: [0.1, 0.2, 0.5, 0.6]
        if not regions:
            coord_tuples = re.findall(
                r"\[\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\]",
                vlm_text,
            )
            for c in coord_tuples:
                vals = [float(v) for v in c]
                scale = 1000.0 if max(vals) > 1.0 else 1.0
                regions.append(
                    BoundingBox(
                        x0=vals[0] / scale,
                        y0=vals[1] / scale,
                        x1=vals[2] / scale,
                        y1=vals[3] / scale,
                        coordinate_space="normalized_page",
                    )
                )

        return GroundingProposal(
            claim_id=f"claim_{evidence_id}",
            evidence_id=evidence_id,
            regions=regions[:4],
            proposer_model_id=model_id,
        )

    @classmethod
    def resolve_regions_from_proposal(
        cls,
        proposal: GroundingProposal,
        parent_page_box: BoundingBox,
        document_id: str,
        page_number: int,
        default_verification: Literal["SUPPORTED", "UNCERTAIN", "CONTRADICTED"] = "SUPPORTED",
    ) -> list[VisualRegion]:
        resolved: list[VisualRegion] = []
        for index, raw_box in enumerate(proposal.regions, start=1):
            valid_crop_box = VisualGroundingValidator.validate_crop_box(raw_box)
            if not valid_crop_box:
                continue

            page_box = VisualGroundingValidator.map_crop_to_page(valid_crop_box, parent_page_box)

            resolved.append(
                VisualRegion(
                    region_id=f"VR_{proposal.evidence_id}_{index:02d}",
                    parent_evidence_id=proposal.evidence_id,
                    document_id=document_id,
                    page=page_number,
                    role="plot",
                    bbox_parent_normalized=valid_crop_box,
                    bbox_page_normalized=page_box,
                    proposal_source="vlm",
                    proposer_model_id=proposal.proposer_model_id,
                    verification=default_verification,
                )
            )
        return resolved
