"""Retired compatibility entry point for pre-release paper figures.

Claim-bearing figures must be generated by the release-bound scripts in
``paper/eacl_industry/figs``. This file remains only to fail loudly for anyone
using the former command.
"""

LEGACY_FIGURE_ENTRYPOINT_RETIRED = True


def main() -> int:
    raise SystemExit(
        "This figure entry point is retired because it accepted unsealed inputs. "
        "Use paper/eacl_industry/figs/* with current measured release data."
    )


if __name__ == "__main__":
    main()
