"""Atomic Claim Verification & Entailment Schemas for ScholAR.

Defines:
- EntailmentStatus: 3-Way Entailment (SUPPORTED, UNSUPPORTED, CONTRADICTED)
- RepairAction: Exactly one conservative repair pass (CITATION_REMAP, CLAIM_NARROWING, NUMERIC_CORRECTION, CLAIM_DELETION)
- AtomicClaim: Granular claim with evidence grounding and repair state
- VerificationReport: Complete factual verification summary and calibrated abstention
"""

from __future__ import annotations

from enum import Enum
from typing import Any
from pydantic import BaseModel, Field


class EntailmentStatus(str, Enum):
    """3-Way Natural Language Inference Entailment Classification."""
    SUPPORTED = "SUPPORTED"          # Factually entailed by cited evidence block
    UNSUPPORTED = "UNSUPPORTED"      # Evidence is silent or incomplete
    CONTRADICTED = "CONTRADICTED"    # Directly contradicted by paper data or text


class RepairAction(str, Enum):
    """Conservative 1-Pass repair actions."""
    NONE = "none"
    CITATION_REMAP = "citation_remap"        # Reconnect claim to correct retrieved block
    CLAIM_NARROWING = "claim_narrowing"      # Add caveat or weaken overclaim
    NUMERIC_CORRECTION = "numeric_correction" # Replace hallucinated number with exact table cell Decimal
    CLAIM_DELETION = "claim_deletion"        # Remove completely unsupported statement
    ABSTAIN = "abstain"                      # Calibrated refusal when evidence is absent


class AtomicClaim(BaseModel):
    """Atomic scientific statement generated by the model with provenance."""
    claim_id: str                            # e.g., "C1", "C2"
    text: str
    cited_evidence_ids: list[str] = Field(default_factory=list)
    entailment_status: EntailmentStatus = EntailmentStatus.SUPPORTED
    confidence_score: float = 1.0
    rationale: str = ""
    repaired_text: str | None = None
    repair_action: RepairAction = RepairAction.NONE


class VerificationReport(BaseModel):
    """Aggregated factual verification report for generated response."""
    claims: list[AtomicClaim] = Field(default_factory=list)
    overall_supported: bool = True
    supported_count: int = 0
    unsupported_count: int = 0
    contradicted_count: int = 0
    has_abstained: bool = False
    abstention_reason: str | None = None
    final_verified_response: str = ""
