.PHONY: all verify draft submission clean

all: draft

verify:
	$(MAKE) -C eacl_industry verify

draft:
	$(MAKE) -C eacl_industry draft

submission:
	$(MAKE) -C eacl_industry submission

clean:
	$(MAKE) -C eacl_industry clean
